# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-04-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.TextField(default='Earth', max_length=255),
            preserve_default=False,
        ),
    ]
